### PR TITLE
Progress Bar Title

### PR DESCRIPTION
**Pull request by niveuseverto**
This changes allows to present progress bar title (like archive name).

### CODE REVIEW

**Comment by goblinfactory** [comment]
@niveuseverto , thanks for the pull request, much appreciated.
will be back at the home office in a few hours and will test and merge this. 
Cheers, A

**Comment by goblinfactory** [comment]
Hi @niveuseverto 
I'm going to close this pull request as it clashes with a change I want to make in version 3.0 that's coming out soon. There is a simple work-around (actually by design) that allows you to achieve what you want.

Instead of creating the progressBar with a title during construction, simply call `Refresh` immediately after creating the pb. for example

    var pb = new ProgressBar(10);
    pb.Refresh(0, "loading");

this design was on purpose.

The reason I'm not adding in an oveloaded constructor, is because too many constructors causes problems, makes the code harder to refactor and test, and is a big clue that you probably need to create a new class.

In this case, I am guessing that the ***need*** for setting the title up front is because you are probably wanting to use the progress bar to track a single simple process duration. In which case rendering the progress bar across two lines, with a separate place for a title and a separate text showing `item xx of yy` is overkill.

I was in the process of cleaning up the constructors, so that I can make sure that all the first parameters are always the same, and the second are the same etc, which makes reading code using the controls much easier. I can't do this with an extra text field at the end. I took a quick look (branched your pull request and tested) and felt that since you can achieve 100% of what you want, by simply calling `Refresh` immediately afterwards, I will stick with my current roadmap.

In version 3.0 the default `new ProgressBar(10, "cats");` will create  a 1 liner pb. This will be a significant breaking change for anyone already using `ProgressBar` which is why it will only come out in version `3.0`. 

To get the old behavior in version `3.0` you will need to pass in an optional `PbStyle` that will define how the progress bar is rendered. The first 2 styles will be `Simple` and `Extended`. 

Simple will render a pb as follows

> Cats  : (10%) #### 
> Cats : (20%) ########

**Comment by goblinfactory** [comment]
@niveuseverto You can always create a new class in your own project that derives from `ProgressBar` eg

   public static class Progress {

     public static ProgressBar New(string title) { 
          var pb = new ProgressBar(20);
          pb.Refresh(0, title);
          return pb;
     }
   }

**Comment by goblinfactory** [comment]
@niveuseverto  I'll leave this 'open' for a while until you've had a chance to comment, ... I'm always keen to have folk want to contribute to the project.

**Comment by niveuseverto** [comment]
Creator with static class produces this output:
creator
My code allows to display this output:
pull request

**Comment by goblinfactory** [comment]
Hi Aexander

Looking into this now.
Can I ask a big favour... is it possible for you to write a small bit of
code that always gives this error?
Ideally a unit test, otherwise a manual eyeball test is also helpful.

<http://www.goblinfactory.co.uk>regards

Alan


*Alan Hemmings*

Goblinfactory.co.uk <http://www.goblinfactory.co.uk/>
https://about.me/alanhemmings

Tel - 07734157754
*cambridge based hacker, coder, investor*

**Comment by niveuseverto** [comment]
Will check into this. But hardly got idea how to test Y coord of progress bar.
As creator method - not leaving title above progress bar, just changes line below.

My idea of bar:
[Title eq. Archive.zip]
Item [current] of [total] ####
[Current file]

When I tried to make Console.WriteLine(Title) before creating ProgressBar - got same issue with invalid Y coordinate.

May be I did something wrong.

**Comment by goblinfactory** [comment]
Ah ok, I think I get it....

I have a simple answer for you, ( I think ).
Can you please log this as an issue in the issue tracker here, then I can
answer you there. That way if someone else has the same issue, my answers
can become the documentation.

<goog_1341376218>
https://github.com/goblinfactory/konsole/issues

click the "new issue" and I'll deal with it quickly.

;-D

thank you!

cheers,

Alan

**Comment by goblinfactory** [comment]
closing this as no more comments received and proper work around exists. Newer progressbar is coming in the next release as well.

**Pull request closed without merging**
